```{r setup, include=FALSE}
library(dplyr)

knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
options(digits = 5)

df <- read.csv('pokemon_complete.csv') %>% 
  select(-c(height_ft, weight_lbs),
         -starts_with('against_'))
```

```{r}
library(Rtsne)
library(tidyr)
library(highcharter)
library(htmltools)
library(purrr)
library(stringr)

df.common <- subset(df, is_legendary == 'FALSE')
ds.common <- df.common %>% 
  list_parse() %>% 
  map(function(x) {
    x$marker$symbol <- paste0('url(', x$icon, ')')
    x$marker$radius <- 2
    x$color <- case_when(x$is_legendary == 'TRUE' ~ '#ffdf00',
                         TRUE ~ '#77a1e5')
    x$x <- x$base_total
    x$y <- x$capture_rate
    x
  })

df.legendary <- subset(df, is_legendary == 'TRUE')
ds.legendary <- df.legendary %>% 
  list_parse() %>% 
  map(function(x) {
    x$marker$symbol <- paste0('url(', x$icon, ')')
    x$marker$radius <- 2
    x$color <- case_when(x$is_legendary == 'TRUE' ~ '#ffdf00',
                         TRUE ~ '#77a1e5')
    x$x <- x$base_total
    x$y <- x$capture_rate
    x
  })

tooltip <- c('pokedex_number',
             'name', 
             'type', 
             'capture_rate',
             'base_total',
             'hp',
             'attack',
             'defense',
             'speed',
             'sp_attack',
             'sp_defense',
             'height_m',
             'weight_kgs') %>% 
  map(function(x) {
    tags$tr(
      tags$th(str_replace_all(str_to_title(x), '_', ' ')),
      tags$td(style = 'text-align: right;',
              paste0('{point.', x, '}'))
    )
  }) %>% 
  do.call(tagList, .) %>% 
  tagList(
    tags$div(style = 'align-items: center; min-height: 125px; justify-content: center; display: flex;',
             tags$img(src = '{point.sprite}',
                      width = '125px', 
                      height = '125px')
  )) 

highchart() %>% 
  hc_title(text = 'Capture Rate vs. Base Total for all 801 Pokémon') %>% 
  hc_subtitle(text = 'Author: Gabriel Bessa, github.com/gabrielvcbessa/pokemon') %>% 
  hc_xAxis(title = list(text = 'Base Total')) %>% 
  hc_yAxis(title = list(text = 'Capture Rate')) %>% 
  hc_add_series(data = ds.common,
                type = 'scatter',
                label = df.common$name,
                sprite = df.common$sprite,
                name = 'Common',
                color = '#77a1e5') %>% 
  hc_add_series(data = ds.legendary,
                type = 'scatter',
                label = df.legendary$name,
                sprite = df.legendary$sprite,
                icon = df.legendary$icon,
                name = 'Legendary',
                color = '#ffdf00') %>% 
  hc_tooltip(
    useHTML = TRUE,
    borderRadius = 0,
    borderWidth = 2,
    headerFormat = '<table>',
    pointFormat = as.character(tooltip),
    footerFormat = '</table>'
  ) %>%
  hc_add_theme(hc_theme_elementary())
```
